# Generated by Django 5.1 on 2024-08-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_log', '0003_rename_first_name_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/contact_log/'),
        ),
    ]
