# Generated by Django 5.1 on 2024-08-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_log', '0006_alter_rank_options_contact_created_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_user',
            new_name='creating_user',
        ),
    ]
