# Generated by Django 5.1 on 2024-08-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_log', '0007_rename_created_user_contact_creating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
